We have next logging message:2023-03-27 17:06:54,528:ERROR -Exeption
Traceback (most recent call last):
  File "C:\Users\MIRA\PycharmProjects\test\main.py", line 8, in <module>
    print(10/0)
ZeroDivisionError: division by zero
